[package]
name = "threescale"
version = "0.1.0"
authors = ["Rahul Anand <rahulanand16nov@gmail.com>", "Lahiru Udayanga <lahirudesilva.17@cse.mrt.ac.lk>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
