config:
  target: "http://gsoc-int-envoy.dev.3sca.net:9095/"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 600
      arrivalRate: 50
      name: Sustained load
scenarios:
  - flow:
      - get:
          url: "/"
          headers:
            x-app-id: 23f118be
            x-app-key: 44d128988763aee1b0ff0691f9686f7e
 