version: '3.7'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - envoy=$ENVOY
    depends_on:
      - backend_service
    networks:
      - envoymesh
    ports:
      - "9095:9095"
      - "9000:9000"
  
  backend_service:
    image: solsson/http-echo
    networks:
      - envoymesh
    environment:
      - PORT=8000 

networks:
  envoymesh: {}
