name: Dependencies
on:
  push:
    branches:
      - 'dev/'
  pull_request:
    branches:
      - main

jobs:
  audit_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
