name: CI
on:
  push:
    branches:
      - 'dev/'
      - '!main'
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
            # MSRV
          - 1.52.1
        experimental: [false]
        cargo_flags: ['',--all-features]
        include:
          # Stop breakages in nightly to fail the workflow
          - rust: nightly
            experimental: true
            cargo_flags: --all-features

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt
          target: wasm32-unknown-unknown
          override: true

      - uses: actions-rs/cargo@v1

      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-snip
          version: latest
  
      - name: Installing binaryen
        run: sudo apt-get install binaryen

      - name: Building application
        run: make build

  # dependent job added to run after build if it succeeds      
  integration:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
        experimental: [false]
        cargo_flags: [--all-features]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt
          target: wasm32-unknown-unknown
          override: true

      - uses: actions-rs/cargo@v1
      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-snip
          version: latest
      - name: Installing binaryen
        run: sudo apt-get install binaryen
        
      - name: Setting up golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'

      - name: Installing dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go get github.com/stretchr/testify

      # Run gofmt to check the formatting of the go files.    
      - name: Run Fmt
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
          
      # Run vet & lint on the code
      - name: Run vet & lint
        run: |
          go vet ./...
          golint -set_exit_status=1 ./...
      
      - name: Building application
        run: make build CARGO_EXTRA_ARGS=--all-features

      - name: Running Integration tests
        run: make integration    

        